version: '2'

services:
  tarantool:
    container_name: mytarantool
    image: tarantool/tarantool:2.2
    environment:
      TARANTOOL_USER_NAME: "admin"
      TARANTOOL_USER_PASSWORD: "pass"
    ports:
      - 3302:3301