version: '2'

services:
  # tarantool:
  #   container_name: mytarantool
  #   image: tarantool/tarantool:2.2
  #   environment:
  #     TARANTOOL_USER_NAME: "admin"
  #     TARANTOOL_USER_PASSWORD: "pass"
  #   ports:
  #     - 3302:3301

  tarantool3:
    container_name: t3
    image: tarantool/tarantool:2.2
    environment:
      TARANTOOL_REPLICATION: "tarantool3,tarantool4"
      TARANTOOL_USER_NAME: "admin"
      TARANTOOL_USER_PASSWORD: "pass"
    networks:
      - mynet
    ports:
      - "3303:3301"

  tarantool4:
    container_name: t4
    image: tarantool/tarantool:2.2
    environment:
      TARANTOOL_REPLICATION: "tarantool3,tarantool4"
      TARANTOOL_USER_NAME: "admin"
      TARANTOOL_USER_PASSWORD: "pass"
    networks:
      - mynet
    ports:
      - "3304:3301"


networks:
  mynet:
    driver: bridge