version: '2'

# sudo docker run --name t5 -d -p 3303:3301 -v /conf:/var/lib/tarantool tarantool/tarantool:3

services:
  # tarantool:
  #   container_name: mytarantool
  #   image: tarantool/tarantool:2.2
  #   environment:
  #     TARANTOOL_USER_NAME: "admin"
  #     TARANTOOL_USER_PASSWORD: "pass"
  #   ports:
  #     - 3302:3301

  tarantool3:
    container_name: t5
    image: tarantool/tarantool:3
    command: tarantool /usr/local/share/tarantool/app.init.lua
    environment:
      TARANTOOL_REPLICATION: "tarantool3,tarantool4"
      TARANTOOL_USER_NAME: "admin"
      TARANTOOL_USER_PASSWORD: "pass"
    networks:
      - mynet
    ports:
      - "3303:3301"
    volumes:
      - /home/alina/Documents/learning_tarantool/conf:/usr/local/share/tarantool
      # - /home/alina/Documents/learning_tarantool/tar-data:/var/lib/tarantool
  tarantool4:
    container_name: t4
    image: tarantool/tarantool:3
    environment:
      TARANTOOL_REPLICATION: "tarantool3,tarantool4"
      TARANTOOL_USER_NAME: "admin"
      TARANTOOL_USER_PASSWORD: "pass"
    networks:
      - mynet
    ports:
      - "3304:3301"


networks:
  mynet:
    driver: bridge